source(here::here("analysis", "00_region_populations.R"))
source(here::here("analysis", "01_setup.R"))
source(here::here("analysis", "02_unique_products.R"))
source(here::here("analysis", "03_primary_analysis.R"))
source(here::here("analysis", "04_secondary_analysis.R"))
source(here::here("analysis", "05_fp10_analysis.R"))
source(here::here("analysis", "06_combined_analysis.R"))
message("All analyses complete.")
